name: GitHub Actions Build and Deploy Demo

on:
  push:
    branches:
      - pro
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        run: curl http://127.0.0.1:7001/pull?env=pro&name=firstDemo
